spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store?usenicoede=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.fan.store.pojo
  mapper-locations: classpath:mapper/*.xml